#!/usr/bin/env bash
# Boosted Flavor CR - EMJ (electron + muon-jet), using EE.py --signal-scale 1.0
python EE.py --signal-scale 1.0 --hist "Obj_PU_pt(ll)_boosted_e_mujet_Flavor_CR" --ymin 10 --ymax 1e3 --output BoostFLVEMJ_pt --xmin 0 --xmax 1000 --xlabel "Dilepton p_{T} (GeV)" --rebin 50 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_leading_fatjet_pt_boosted_e_mujet_Flavor_CR" --ymin 1 --ymax 3e3 --output BoostFLVEMJ_leading_fatjet_pt --xmin 0 --xmax 2000 --xlabel "Leading Fat Jet p_{T} (GeV)" --bins "200,400,600,800,1000,2000" --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_m(lljj)_boosted_e_mujet_Flavor_CR" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_mlljj --xmin 800 --xmax 8000 --xlabel "m(lljj) (GeV)" --bins "800,1000,1200,1500,1800,8000" --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_Fatjet_SDMass" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_fatjet_SDMass --xmin 0 --xmax 200 --xlabel "Fat Jet Soft Drop Mass (GeV)" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_LeadingLepPt" --ymin 1e-1 --ymax 1e6 --output BoostFLVEMJ_leading_lep_pt --xmin 0 --xmax 1000 --xlabel "Leading Lepton p_{T} (GeV)" --bins "50,90,130,170,210,250,290,310,350,390,430,470,510,550,590,630,670,710,750,790,830,870,910,950,1000,2000" --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_SubLeadingLepPt" --ymin 1e-3 --ymax 1e6 --output BoostFLVEMJ_subleading_lep_pt --xmin 0 --xmax 500 --xlabel "Subleading Lepton p_{T} (GeV)" --bins "50,70,90,110,130,150,170,190,210,230,250,270,290,310,330,350,370,390,410,430,450,470,490,500" --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_LeadingLepEta" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_leading_lep_eta --xmin -2.5 --xmax 2.5 --xlabel "Leading Lepton #eta" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_SubLeadingLepEta" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_subleading_lep_eta --xmin -2.5 --xmax 2.5 --xlabel "Subleading Lepton #eta" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_Fatjet_Eta" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_fatjet_eta --xmin -2.5 --xmax 2.5 --xlabel "Fat Jet #eta" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_Fatjet_Phi" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_fatjet_phi --xmin -3.14 --xmax 3.14 --xlabel "Fat Jet #phi" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR e_mujet_DeltaR_LeadLep_Fatjet" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_deltaR_leadlep_fatjet --xmin 0 --xmax 5 --xlabel "#DeltaR(lead lep, fat jet)" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR e_mujet_LeadLep_LSF" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_leadlep_lsf --xmin 0 --xmax 1 --xlabel "Lead Lep LSF" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR e_mujet_mll" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_mll --xmin 0 --xmax 1000 --xlabel "m(ll) (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR e_mujet_Fatjet_pt" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_fatjet_pt --xmin 0 --xmax 1000 --xlabel "Fat Jet p_{T} (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR e_mujet_WRpt" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_WR_pt --xmin 0 --xmax 1000 --xlabel "WR p_{T} (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_mass" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_mass --xmin 0 --xmax 2000 --xlabel "m(ll) (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_eta" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_eta --xmin -5 --xmax 5 --xlabel "Dilepton #eta" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_phi" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_phi --xmin -3.14 --xmax 3.14 --xlabel "Dilepton #phi" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_WR_eta" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_WR_eta --xmin -5 --xmax 5 --xlabel "WR #eta" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_WR_phi" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_WR_phi --xmin -3.14 --xmax 3.14 --xlabel "WR #phi" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_LeadingLepPhi" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_leading_lep_phi --xmin -3.14 --xmax 3.14 --xlabel "Leading Lepton #phi" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_SubLeadingLepPhi" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_subleading_lep_phi --xmin -3.14 --xmax 3.14 --xlabel "Subleading Lepton #phi" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_Fatjet_lsf3" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_fatjet_lsf3 --xmin 0 --xmax 1 --xlabel "Fat Jet LSF3" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_dphi_leadlep_fatjet" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_dphi_leadlep_fatjet --xmin 0 --xmax 3.14 --xlabel "#Delta#phi(lead lep, fat jet)" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_punum" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_punum --xmin 0 --xmax 80 --xlabel "Number of Pileup Vertices" --rebin 2 --rmin 0 --rmax 2.5
python EE.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_e_mujet_jetnum" --ymin 1 --ymax 1e3 --output BoostFLVEMJ_jetnum --xmin 0 --xmax 20 --xlabel "Number of Jets" --rmin 0 --rmax 2.5

# Boosted Flavor CR - MEJ (muon + electron-jets), using MM.py --signal-scale 1.0
python MM.py --signal-scale 1.0 --hist "Obj_PU_pt(ll)_boosted_mu_ejets_Flavor_CR" --ymin 10 --ymax 1e3 --output BoostFLVMEJ_pt --xmin 0 --xmax 1000 --xlabel "Dilepton p_{T} (GeV)" --rebin 50 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_leading_fatjet_pt_boosted_mu_ejets_Flavor_CR" --ymin 1 --ymax 3e3 --output BoostFLVMEJ_leading_fatjet_pt --xmin 0 --xmax 2000 --xlabel "Leading Fat Jet p_{T} (GeV)" --bins "200,400,600,800,1000,2000" --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_m(lljj)_boosted_mu_ejets_Flavor_CR" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_mlljj --xmin 800 --xmax 8000 --xlabel "m(lljj) (GeV)" --bins "800,1000,1200,1500,1800,8000" --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_Fatjet_SDMass" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_fatjet_SDMass --xmin 0 --xmax 200 --xlabel "Fat Jet Soft Drop Mass (GeV)" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_LeadingLepPt" --ymin 1e-1 --ymax 1e6 --output BoostFLVMEJ_leading_lep_pt --xmin 0 --xmax 1000 --xlabel "Leading Lepton p_{T} (GeV)" --bins "50,90,130,170,210,250,290,310,350,390,430,470,510,550,590,630,670,710,750,790,830,870,910,950,1000" --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_SubLeadingLepPt" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_subleading_lep_pt --xmin 0 --xmax 500 --xlabel "Subleading Lepton p_{T} (GeV)" --bins "50,70,90,110,130,150,170,190,210,230,250,270,290,310,330,350,370,390,410,430,450,470,490,500" --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_LeadingLepEta" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_leading_lep_eta --xmin -2.5 --xmax 2.5 --xlabel "Leading Lepton #eta" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_SubLeadingLepEta" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_subleading_lep_eta --xmin -2.5 --xmax 2.5 --xlabel "Subleading Lepton #eta" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_Fatjet_Eta" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_fatjet_eta --xmin -2.5 --xmax 2.5 --xlabel "Fat Jet #eta" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_Fatjet_Phi" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_fatjet_phi --xmin -3.14 --xmax 3.14 --xlabel "Fat Jet #phi" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR mu_ejets_DeltaR_LeadLep_Fatjet" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_deltaR_leadlep_fatjet --xmin 0 --xmax 5 --xlabel "#DeltaR(lead lep, fat jet)" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR mu_ejets_LeadLep_LSF" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_leadlep_lsf --xmin 0 --xmax 1 --xlabel "Lead Lep LSF" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR mu_ejets_mll" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_mll --xmin 0 --xmax 1000 --xlabel "m(ll) (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR mu_ejets_Fatjet_pt" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_fatjet_pt --xmin 0 --xmax 1000 --xlabel "Fat Jet p_{T} (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR mu_ejets_WRpt" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_WR_pt --xmin 0 --xmax 1000 --xlabel "WR p_{T} (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_mass" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_mass --xmin 0 --xmax 2000 --xlabel "m(ll) (GeV)" --rebin 5 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_eta" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_eta --xmin -5 --xmax 5 --xlabel "Dilepton #eta" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_phi" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_phi --xmin -3.14 --xmax 3.14 --xlabel "Dilepton #phi" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_WR_eta" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_WR_eta --xmin -5 --xmax 5 --xlabel "WR #eta" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_WR_phi" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_WR_phi --xmin -3.14 --xmax 3.14 --xlabel "WR #phi" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_LeadingLepPhi" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_leading_lep_phi --xmin -3.14 --xmax 3.14 --xlabel "Leading Lepton #phi" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_SubLeadingLepPhi" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_subleading_lep_phi --xmin -3.14 --xmax 3.14 --xlabel "Subleading Lepton #phi" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_Fatjet_lsf3" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_fatjet_lsf3 --xmin 0 --xmax 1 --xlabel "Fat Jet LSF3" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_dphi_leadlep_fatjet" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_dphi_leadlep_fatjet --xmin 0 --xmax 3.14 --xlabel "#Delta#phi(lead lep, fat jet)" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_punum" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_punum --xmin 0 --xmax 80 --xlabel "Number of Pileup Vertices" --rebin 2 --rmin 0 --rmax 2.5
python MM.py --signal-scale 1.0 --hist "Obj_PU_Boosted_Flavor_CR_mu_ejets_jetnum" --ymin 1 --ymax 1e3 --output BoostFLVMEJ_jetnum --xmin 0 --xmax 20 --xlabel "Number of Jets" --rmin 0 --rmax 2.5
