
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/data6/Users/achihwan/miniforge3/envs/Nano/lib/python3.12/site-packages/cmake/data/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/data6/Users/achihwan/miniforge3/envs/Nano/bin/"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/sbin/"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/x86_64-conda-linux-gnu/sysroot/usr/bin/"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/x86_64-conda-linux-gnu/sysroot/usr/sbin/"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/x86_64-conda-linux-gnu/sysroot/usr/"
      - "/home/achihwan/SKNanoAnalyzer/python/"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/bin/"
      - "/data6/Users/achihwan/miniforge3/condabin/"
      - "/home/achihwan/.local/bin/"
      - "/home/achihwan/bin/"
      - "/cvmfs/cms.cern.ch/common/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/usr/local/sbin/"
      - "/usr/sbin/"
      - "/opt/pbs/bin/"
      - "/var/lib/snapd/snap/bin/"
      - "/home/achihwan/SKNanoAnalyzer/external/lhapdf/redhat/bin/"
      - "/bin/"
    searched_directories:
      - "/data6/Users/achihwan/miniforge3/envs/Nano/bin/uname"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/sbin/uname"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/uname"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/x86_64-conda-linux-gnu/sysroot/usr/bin/uname"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/x86_64-conda-linux-gnu/sysroot/usr/sbin/uname"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/x86_64-conda-linux-gnu/sysroot/usr/uname"
      - "/home/achihwan/SKNanoAnalyzer/python/uname"
      - "/data6/Users/achihwan/miniforge3/envs/Nano/bin/uname"
      - "/data6/Users/achihwan/miniforge3/condabin/uname"
      - "/home/achihwan/.local/bin/uname"
      - "/home/achihwan/bin/uname"
      - "/cvmfs/cms.cern.ch/common/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{CMAKE_PREFIX_PATH}:
        - "/data6/Users/achihwan/miniforge3/envs/Nano"
        - "/data6/Users/achihwan/miniforge3/envs/Nano/x86_64-conda-linux-gnu/sysroot/usr"
      ENV{PATH}:
        - "/home/achihwan/SKNanoAnalyzer/python"
        - "/data6/Users/achihwan/miniforge3/envs/Nano/bin"
        - "/data6/Users/achihwan/miniforge3/condabin"
        - "/home/achihwan/.local/bin"
        - "/home/achihwan/bin"
        - "/cvmfs/cms.cern.ch/common"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/usr/local/sbin"
        - "/usr/sbin"
        - "/opt/pbs/bin"
        - "/var/lib/snapd/snap/bin"
        - "/home/achihwan/SKNanoAnalyzer/external/lhapdf/redhat/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/data6/Users/achihwan/miniforge3/envs/Nano/lib/python3.12/site-packages/cmake/data/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.14.0-503.31.1.el9_5.x86_64 - x86_64
...
