#!/usr/bin/env python3
"""
Split HNWR skim work over HTCondor.

Resolves sample aliases to their NanoAOD file lists via
$SKNANO_DATA/<era>/Sample/ForSNU/<alias>.json, chunks them, and submits one
condor job per chunk running skim_hnwr.py inside the singularity image.

This does not go through SKNano.py and does not need the SKNanoAnalyzer build.

  # see what would happen
  ./submit_skim.py --era 2023 --samples TTLL_powheg --files-per-job 5 --dry-run

  # background MC, 5 input files per job
  ./submit_skim.py --era 2023 --samples-from bkg.txt --files-per-job 5

  # everything matching a pattern
  ./submit_skim.py --era 2023 --samples 'DYMLL*' 'TTLL_powheg' 'WJetM*'

Output lands in
  <--outbase>/<era>/{MC,DATA}/Skim/$USER/Skim_HNWR_<alias>/tree_<i>.root
which mirrors the layout SKNano.py's own skimming mode uses. Register the
result with register_skim.py so `SKNano.py -i 'Skim_HNWR_*'` can find it.
"""

import argparse
import fnmatch
import glob
import json
import os
import stat
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import skim_naming  # noqa: E402

RUN_SH = """#!/bin/bash
# Auto-generated by submit_skim.py -- runs one skim chunk.
export PATH={conda_bin}:$PATH
export MAMBA_ROOT_PREFIX={mamba_root}
eval "$(micromamba shell hook -s bash)"
micromamba activate {mamba_env}

python3 {skim_py} \\
    --era {era} \\
    --filelist {workdir}/filelist_$1.txt \\
    --output {outdir}/tree_$1.root \\
    --report-json {workdir}/report_$1.json \\
    --threads {threads} \\
    --compression {compression} \\
    --compression-level {complevel} {extra}
exit $?
"""

SUBMIT = """universe                = vanilla
executable              = {workdir}/run.sh
+singularityimage       = "{image}"
arguments               = $(Process)
output                  = {workdir}/log/job_$(Process).out
error                   = {workdir}/log/job_$(Process).err
log                     = {workdir}/log/condor.log
RequestCpus             = {threads}
RequestMemory           = {memory} MB
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
periodic_release        = (NumJobStarts < 5) && (HoldReasonCode == 34 || HoldReasonCode == 21) && (JobStatus == 5)
JobBatchName            = SkimHNWR_{era}_{sample}
{concurrency}queue {njobs}
"""
# NOTE: no bare `concurrency_limits = 300` here. templates/job_dict.py has that,
# but it only works because SKNano.py feeds the dict to the htcondor python
# bindings. In a .sub file the value must be a limit NAME, optionally with a
# count ("mylimit:300"), and a bare number is rejected:
#     ERROR: Invalid concurrency limit '300'
# Pass --concurrency NAME:N if your pool actually defines one.


def sample_dir(era):
    data = os.environ.get("SKNANO_DATA")
    if not data:
        sys.exit("SKNANO_DATA is not set -- source setup.sh, or pass --sample-dir")
    return os.path.join(data, era, "Sample")


def resolve_samples(patterns, sampledir):
    """Expand shell-style patterns against the ForSNU JSON filenames."""
    known = sorted(
        os.path.basename(p)[:-5]
        for p in glob.glob(os.path.join(sampledir, "ForSNU", "*.json"))
    )
    out = []
    for pat in patterns:
        hits = fnmatch.filter(known, pat) if any(c in pat for c in "*?[") else (
            [pat] if pat in known else []
        )
        if not hits:
            sys.exit(f"no sample matches '{pat}' in {sampledir}/ForSNU")
        out += hits
    return sorted(set(out))


def chunk(seq, n):
    return [seq[i:i + n] for i in range(0, len(seq), n)]


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--era", required=True)
    p.add_argument("--samples", nargs="*", default=[],
                   help="aliases or glob patterns, e.g. 'DYMLL*'")
    p.add_argument("--samples-from", help="text file with one alias/pattern per line")
    p.add_argument("--files-per-job", type=int, default=5)
    p.add_argument("--threads", type=int, default=1)
    p.add_argument("--memory", type=int, default=4000)
    p.add_argument("--suffix", default="HNWR", help="skim tag -> Skim_<suffix>_<alias>")
    p.add_argument("--compression", default="zstd")
    p.add_argument("--compression-level", type=int, default=5)
    p.add_argument("--drop", nargs="*", default=[],
                   help="regexes of Events branches to drop (default: keep all)")
    p.add_argument("--sample-dir", help="override $SKNANO_DATA/<era>/Sample")
    p.add_argument("--outbase", default=os.environ.get(
        "SKNANO_RUN3_NANOAODPATH", "/gv0/DATA/SKNano/Run3NanoAODv12"))
    p.add_argument("--workbase", default=os.path.join(
        os.environ.get("SKNANO_RUNLOG", "/tmp"), "SkimHNWR"))
    p.add_argument("--image", default=os.environ.get(
        "SINGULARITY_IMAGE", "/data6/Users/achihwan/private-el9.sif"))
    p.add_argument("--conda-bin", default="/opt/conda/bin",
                   help="micromamba bin dir inside the image (SKNano.py:435 uses /opt/conda)")
    p.add_argument("--mamba-root", default="/opt/conda")
    p.add_argument("--mamba-env", default="Nano")
    p.add_argument("--concurrency", default=None, metavar="NAME:N",
                   help="condor concurrency_limits, e.g. 'skim:10'. Must be a limit "
                        "NAME (a bare number is rejected by condor_submit). Omitted "
                        "by default.")
    p.add_argument("--dry-run", action="store_true",
                   help="print what would be submitted, write nothing")
    p.add_argument("--validate", action="store_true",
                   help="write the submit files and run condor_submit -dry-run on "
                        "them instead of really queueing")
    args = p.parse_args()

    if args.concurrency and args.concurrency.split(":")[0].isdigit():
        sys.exit(f"--concurrency '{args.concurrency}' starts with a number; condor "
                 "needs a limit NAME, e.g. 'skim:10'")

    patterns = list(args.samples)
    if args.samples_from:
        with open(args.samples_from) as fh:
            patterns += [ln.strip() for ln in fh if ln.strip() and not ln.startswith("#")]
    if not patterns:
        sys.exit("give --samples and/or --samples-from")

    sampledir = args.sample_dir or sample_dir(args.era)
    samples = resolve_samples(patterns, sampledir)
    print(f"[submit] {len(samples)} sample(s): {', '.join(samples)}\n")

    user = os.environ.get("USER", "unknown")
    total_jobs = 0

    for alias in samples:
        info = json.load(open(os.path.join(sampledir, "ForSNU", alias + ".json")))
        paths = info["path"]
        chunks = chunk(paths, args.files_per_job)

        outdir = skim_naming.output_dir(args.outbase, args.era, args.suffix, alias, user)
        workdir = os.path.join(args.workbase, args.era,
                               skim_naming.json_name(args.suffix, alias))

        print(f"  {alias:<32} {len(paths):>5} files -> {len(chunks):>4} jobs")
        print(f"      out  {outdir}")

        if args.dry_run:
            total_jobs += len(chunks)
            continue

        if os.path.isdir(outdir) and os.listdir(outdir):
            sys.exit(
                f"\n{outdir} already exists and is not empty.\n"
                "Delete it before re-skimming -- leftover files from a previous run "
                "would be picked up by register_skim.py and double-count events."
            )
        os.makedirs(outdir, exist_ok=True)
        os.makedirs(os.path.join(workdir, "log"), exist_ok=True)

        for i, files in enumerate(chunks):
            with open(os.path.join(workdir, f"filelist_{i}.txt"), "w") as fh:
                fh.write("\n".join(files) + "\n")

        extra = ("--drop " + " ".join(f"'{d}'" for d in args.drop)) if args.drop else ""
        run_sh = os.path.join(workdir, "run.sh")
        with open(run_sh, "w") as fh:
            fh.write(RUN_SH.format(
                conda_bin=args.conda_bin, mamba_root=args.mamba_root,
                mamba_env=args.mamba_env, skim_py=os.path.join(HERE, "skim_hnwr.py"),
                era=args.era, workdir=workdir, outdir=outdir, threads=args.threads,
                compression=args.compression, complevel=args.compression_level,
                extra=extra))
        os.chmod(run_sh, os.stat(run_sh).st_mode | stat.S_IEXEC | stat.S_IXGRP)

        sub_path = os.path.join(workdir, "submit.sub")
        conc = (f"concurrency_limits      = {args.concurrency}\n"
                if args.concurrency else "")
        with open(sub_path, "w") as fh:
            fh.write(SUBMIT.format(
                workdir=workdir, image=args.image, threads=args.threads,
                memory=args.memory, njobs=len(chunks), era=args.era, sample=alias,
                concurrency=conc))

        cmd = (["condor_submit", "-dry-run", os.devnull, sub_path] if args.validate
               else ["condor_submit", sub_path])
        subprocess.run(cmd, check=True)
        total_jobs += len(chunks)

    state = ("would be submitted" if args.dry_run
             else "validated, NOT submitted" if args.validate
             else "submitted")
    print(f"\n[submit] {total_jobs} job(s) {state}")
    if not args.dry_run and not args.validate:
        print("[submit] when they finish, register with:")
        print(f"    ./register_skim.py --era {args.era} --suffix {args.suffix} "
              f"--samples {' '.join(samples)}")


if __name__ == "__main__":
    main()
